### ISSUE TITLE
Failed to run on RTX 3080 Ti

### ISSUE THREAD

**Issue by ansarker** [RuiLiFeng/Deep-Generative-Projection#8]
Using TensorFlow backend.
2022-06-22 16:32:28.334844: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
Setting up TensorFlow plugin "fused_bias_act.cu": Preprocessing... 2022-06-22 16:32:28.879151: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1663] Cannot dlopen some GPU libraries. Skipping registering GPU devices...
Failed!
Traceback (most recent call last):
  File "deepGenPro.py", line 144, in <module>
    main(args)
  File "deepGenPro.py", line 53, in main
    args.E, args.D, args.Gs = misc.load_pkl(network_pkl) # Encoder, Discriminator, Generator
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/training/misc.py", line 30, in load_pkl
    return pickle.load(file, encoding='latin1')
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/network.py", line 297, in __setstate__
    self._init_graph()
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/network.py", line 154, in _init_graph
    out_expr = self._build_func(*self.input_templates, **build_kwargs)
  File "<string>", line 362, in Encoder
  File "<string>", line 258, in apply_bias_act
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/ops/fused_bias_act.py", line 68, in fused_bias_act
    return impl_dict[impl](x=x, b=b, axis=axis, act=act, alpha=alpha, gain=gain)
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/ops/fused_bias_act.py", line 122, in _fused_bias_act_cuda
    cuda_kernel = _get_plugin().fused_bias_act
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/ops/fused_bias_act.py", line 16, in _get_plugin
    return custom_ops.get_plugin(os.path.splitext(__file__)[0] + '.cu')
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/custom_ops.py", line 131, in get_plugin
    compile_opts += ' --gpu-architecture=%s' % _get_cuda_gpu_arch_string()
  File "/home/anis/Virtual_Trial_Room/codes/Deep-Generative-Projection/dnnlib/tflib/custom_ops.py", line 52, in _get_cuda_gpu_arch_string
    raise RuntimeError('No GPU devices found')
RuntimeError: No GPU devices found

**Comment by Mukil07** [comment]
Im having the same issues with RTX 2080Ti, how did you resolve this ?

**Comment by RuiLiFeng** [comment]
> Im having the same issues with RTX 2080Ti, how did you resolve this ?

Did you set the environments according to readme? What's your cuda version and tf version?

**Comment by RuiLiFeng** [comment]
It seems the GPU is not consistent with the cuda and tf.

**Comment by Mukil07** [comment]
yeah thanks, I got it resolved. I had some issues with the tensorflow-gpu version mismatch.
